[package]
name = "macro-kwargs"
version.workspace = true
description = "Keyword argument parsing for function-like proc-macros"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
quote = "1"
indexmap = "2"
macro-kwargs-derive = { version = "0.3.0", path = "lib/derive" }
proc-macro2.workspace = true
syn.workspace = true

[dev-dependencies]
trybuild = "1"
macro-kwargs-test-macros = { path = "lib/test-macros" }

[lints]
workspace = true

[workspace]
resolver = "2"
members = [".", "lib/derive", "lib/test-macros"]
default-members = [".", "lib/derive", "lib/test-macros"]

[workspace.package]
version = "0.3.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Techcable/macro-kwargs.rs"
# 1.56 - 2021 edition
# 1.64 - workspace.package
# 1.71 - syn@3
rust-version = "1.71"
keywords = ["macro", "kwargs", "function", "parse", "args"]
categories = ["development-tools::procedural-macro-helpers", "parsing"]
readme = "README.md"

[workspace.dependencies]
proc-macro2 = { version = "1", default-features = false }

[workspace.dependencies.syn]
version = "3"
default-features = false
features = ["parsing", "printing", "derive", "extra-traits"]

[workspace.lints.clippy]
## groups ##
pedantic = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

# excessively pedantic
inconsistent_struct_constructor = "allow"
default_trait_access = "allow"
needless_raw_string_hashes = "allow"
too_many_lines = "allow"
needless_continue = "allow"
redundant_else = "allow"

[workspace.metadata.cargo-reedme]
note = "Do not edit - automatically generated by cargo-reedme"
