[package]
name = "macro-kwargs-derive"
version.workspace = true
description = "Procedural derive for macro-kwargs"
edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["proc-macro"] }
proc-macro2 = { workspace = true, features = ["proc-macro"] }
heck = "0.5"
quote = "1"

